ktor:
  deployment:
    port: 54676
    host: 0.0.0.0
  application:
    modules:
      - "com.milkcocoa.info.shochu_club.ApplicationKt.apiModule"
  database:
    db: $MARIADB_DATABASE
    host: $MARIADB_HOST
    port: $MARIADB_EXPOSED_PORT
    driver: JdbcMariadb
    user: $MARIADB_USER
    password: $MARIADB_PASSWORD
    flyway:
      locations:
        - "classpath:db/migration"
  cache:
    host: $REDIS_HOST
    port: $REDIS_PORT