ktor:
  deployment:
    port: 54676
    host: 0.0.0.0
  application:
    modules:
      - "com.milkcocoa.info.shochu_club.ApplicationKt.apiModule"
  database:
    db: $API_DB_DATABASE
    host: $API_DB_HOST
    port: $API_DB_EXPOSED_PORT
    driver: JdbcPostgres
    user: $API_DB_USER
    pool:
      min: 10
      max: 50
      idle: 1200
      lifetime: 1800
    password:
      # value: 生の値
      value: $API_DB_PASSWORD
      # パスワード生成器
      provider:
        # 生成器の種類
        # Raw: そのまま使用する
        # ASM: AWS Secret Managerを使用する
        type: Raw
        # Optional
        # AWS Secret Managerを用いる場合に必須
        secret: ""
        region: ""
    flyway:
      locations:
        - "classpath:db/migration"
  cache:
    host: $REDIS_HOST
    port: $REDIS_PORT
  storage:
#    key: $ACCESS_KEY_ID
#    secret: $ACCESS_SECRET
    bucket: $API_STORAGE_BUCKET
    region: $API_STORAGE_REGION
    # S3 エンドポイントを使用してバケットにアクセスする際に利用
    endpoint: $API_STORAGE_ENDPOINT
    distribute:
      # コンテンツ配信のタイプ
      # Direct: バケットからそのまま配信する。
      # CDN: CloudFrontなどを用いて配信する
      type: Direct
      # typeがCDNのときのオリジン
      origin: ""
      # 署名をするかどうか
      sign: false
      # 署名の有効期限（秒）
      lifetime: 0
